### ISSUE TITLE
Doesn't seem to run in a bash terminal session

### ISSUE THREAD

**Issue by ShepBoi** [sam-the-programmer/sandcastle#2]
![image](https://github.com/sam-the-programmer/sandcastle/assets/65041792/b261e14b-1f6c-410f-b4dd-84d325d9edee)
It doesn't seem to like working inside a bash terminal in Linux (Fedora 38 in this case).

Also, what is a good free IDE for Go? I can't use visual studio as I am on Linux, but I could try learning some Go so that I could try and fix it to run on my system. I would prefer if the IDE is open source, but it's not a massive deal. I was planning to use KDevelop but the Go plugin is unmaintained

**Comment by ShepBoi** [comment]
Also the first error that said "permission denied" is due to me not marking as executable
It appears that it's looking for a text file that I don't have, do I require the source code for this?

Edit: I'm a muppet I forgot to make a config file... Complete user error

**Comment by s4m-mo** [comment]
1. Good free IDE for linux is VS Code with the Go extension installed
2. I plan to have a `castle init` feature but it is not working atm
